service: building-a-serverless-rest-api-with-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: eu-central-1
  
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: notes
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: notes
         method: get
         cors: true
  update:
    handler: handler.update
    events:
     - http:
         path: notes/{id}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: notes/{id}
         method: delete
         cors: true

plugins:
- serverless-offline